// website/src/components/CopyText.tsx
import { useEffect, useRef, useState } from "react";
import cx from "../cx";
import ActionBar from "./ActionBar";
import ContentCopyIcon from "mdi-react/ContentCopyIcon";
import { CopyToClipboard } from "react-copy-to-clipboard";

export default function CopyText({
  copyText, // TODO:
  ...props
}: React.ComponentProps<typeof ActionBar> & { copyText: string }) {
  const [copyState, setCopyState] = useState<boolean | undefined>();
  const refTextInput = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    const timeout = setTimeout(() => setCopyState(undefined), 1000);

    return () => clearTimeout(timeout);
  }, [copyState]);

  const copySuccess = () => {
    setCopyState(true);
    refTextInput.current?.focus();
  };
  const copyError = () => {
    setCopyState(false);
  };

  return (
    <ActionBar {...props}>
      <input
        ref={refTextInput}
        className={cx`gitpkg-input with-right ${copyState === true && "success"}`}
        style={{ flex: "1 1 auto" }}
        type="text"
        value={copyText}
        readOnly
      />
      <CopyToClipboard
        text={copyText}
        onCopy={(_, success) => (success ? copySuccess() : copyError())}
      >
        <button
          className={cx`gitpkg-button icon with-left ${{
            success: copyState === true,
            error: copyState === false,
          }}`}
          type="button"
        >
          <ContentCopyIcon size={16} />
        </button>
      </CopyToClipboard>
    </ActionBar>
  );
}

// docs/.vuepress/my-components/CopyText.vue
<template>
  <action-bar>
    <template #prepend="data">
      <slot name="prepend" v-bind="data" />
    </template>
    <input
      ref="textInput"
      class="copy-text-input gitpkg-input with-right"
      :class="{ success: copyState === true }"
      type="text"
      :value="text"
      readonly
    />
    <button
      class="gitpkg-button icon with-left"
      :class="{
        success: copyState === true,
        error: copyState === false,
      }"
      type="button"
      v-clipboard:copy="text"
      v-clipboard:success="copySuccess"
      v-clipboard:error="copyError"
    >
      <content-copy width="16" height="16" />
    </button>
  </action-bar>
</template>

<script>
import ContentCopy from "mdi-vue/ContentCopy.vue";
import ActionBar from "./ActionBar";

export default {
  components: {
    ContentCopy,
    ActionBar,
  },
  props: {
    text: String,
  },
  data() {
    return {
      copyState: undefined,
      resetTask: undefined,
    };
  },
  methods: {
    copyEnd(success) {
      this.copyState = !!success;

      if (this.resetTask !== undefined) clearTimeout(this.resetTask);
      this.resetTask = setTimeout(() => {
        this.copyState = undefined;
        this.resetTask = undefined;
      }, 1000);
    },
    copySuccess() {
      this.copyEnd(true);
      this.$refs.textInput.focus();
    },
    copyError() {
      this.copyEnd(false);
    },
  },
};
</script>

<style lang="stylus" scoped>
.copy-text-input
  flex 1 1 auto
</style>
