// website/src/components/GitPkgApi.tsx
import CloseIcon from "mdi-react/CloseIcon";
import GithubIcon from "mdi-react/GithubIcon";
import { apiFromUrl } from "../gitpkg/api-from-url";
import ApiChoicesDisplay from "./ApiChoicesDisplay";
import SingleApiDisplay from "./SingleApiDisplay";
import CustomScripts from "./CustomScripts";
import ActionBar from "./ActionBar";
import { useState } from "react";
import cx from "../cx";
import { CustomScript } from "./CustomScriptEdit";

import styles from "./GitPkgApi.module.scss";

const DEFAULT_PLACEHOLDER =
  "https://github.com/<user>/<repo>/tree/<commit>/<subdir>";

export default function GitPkgApi() {
  // github tree url
  const [url, setUrl] = useState("");

  const placeholder = DEFAULT_PLACEHOLDER;

  const preview = !url;
  const urlToDisplay = url || placeholder;

  const [customScripts, setCustomScripts] = useState<CustomScript[]>([]);

  const api = apiFromUrl(urlToDisplay, customScripts);
  const error = api.data.originalUrl && api.type === "error";
  return (
    <div className={cx`${styles.container} ${preview && styles.preview}`}>
      <div className={styles.inputContainer}>
        <ActionBar
          text="Just paste your github url and copy the commands:"
          Prepend={GithubIcon}
        >
          <input
            className={cx`gitpkg-input with-right ${styles.mainInput} ${error && "error"}`}
            autoFocus
            value={url}
            onChange={e => setUrl(e.target.value)}
            placeholder={placeholder}
          />
          <button
            className="gitpkg-button icon with-left"
            type="button"
            onClick={() => setUrl("")}
          >
            <CloseIcon size={16} />
          </button>
        </ActionBar>
      </div>
      <CustomScripts {...{ customScripts, setCustomScripts }} />
      {api.type === "choice" ? (
        <ApiChoicesDisplay apiList={api.possibleApis} />
      ) : (
        <SingleApiDisplay
          api={api}
          style={{
            minHeight: "20em",
            marginTop: "1.4em",
          }}
        />
      )}
    </div>
  );
}

// docs/.vuepress/components/GitpkgApi.vue
<template>
  <div
    class="gitpkg-container"
    :class="{
      'gitpkg-preview': preview,
    }"
  >
    <div class="input-container">
      <action-bar>
        <template #text>
          Just paste your github url and copy the commands:
        </template>
        <template #prepend="{ size }">
          <github-icon :width="size" :height="size" />
        </template>
        <input
          class="gitpkg-input main-input with-right"
          :class="{ error }"
          autofocus
          v-model="url"
          :placeholder="placeholder"
        />
        <button
          class="gitpkg-button icon with-left"
          type="button"
          @click="url = ''"
        >
          <close-icon width="16" height="16" />
        </button>
      </action-bar>
    </div>
    <custom-scripts v-model="customScripts" />
    <api-choices-display
      v-if="api.type === 'choice'"
      :apiList="api.possibleApis"
    />
    <single-api-display
      v-else
      :api="api"
      style="min-height: 20em; margin-top: 1.4em;"
    />
  </div>
</template>

<script>
import CloseIcon from "mdi-vue/Close.vue";
import GithubIcon from "mdi-vue/Github.vue";
import { apiFromUrl } from "../api-from-url";
import ApiChoicesDisplay from "../my-components/ApiChoicesDisplay.vue";
import SingleApiDisplay from "../my-components/SingleApiDisplay.vue";
import CustomScripts from "../my-components/CustomScripts.vue";
import ActionBar from "../my-components/ActionBar.vue";

export default {
  components: {
    ApiChoicesDisplay,
    SingleApiDisplay,
    CustomScripts,
    CloseIcon,
    GithubIcon,
    ActionBar,
  },
  data() {
    return {
      // github tree url
      url: "",
      placeholder: "https://github.com/<user>/<repo>/tree/<commit>/<subdir>",
      customScripts: [],
    };
  },
  computed: {
    api() {
      return apiFromUrl(this.url || this.placeholder, this.customScripts);
    },
    preview() {
      return !this.url;
    },
    error() {
      return this.api.data.originalUrl && this.api.type === "error";
    },
  },
};
</script>

<style lang="stylus" scoped>
.gitpkg-container
  max-width 40em
  margin 1em auto

  &.gitpkg-preview > :not(.input-container),
  &.gitpkg-preview > :not(.input-container) >>> *
    color lightgrey

.input-container
  display flex
  align-items center

  .main-input
    flex 1 1 auto
</style>
