// docs/.vuepress/my-components/CustomScripts.vue
<template>
  <action-bar>
    <template #prepend="{ size }">
      <wrench-outline-icon :width="size" :height="size" />
    </template>
    <template #text>
      Custom Scripts
      <div style="margin-bottom: 1.4em">
        <custom-script-edit
          v-for="(cs, i) in customScripts"
          :key="cs.__key"
          v-model="customScripts[i]"
          @remove="removeCustomScript(i)"
        />
      </div>
    </template>
    <button
      class="gitpkg-button"
      style="flex: 1 1 0"
      type="button"
      @click="addCustomScript"
    >
      Add a custom script
    </button>
    <button
      class="gitpkg-button icon with-left"
      type="button"
      @click="seeCustomScriptHelp"
    >
      <help-icon width="16" height="16" />
    </button>
  </action-bar>
</template>

<script>
import ActionBar from "./ActionBar.vue";
import CustomScriptEdit from "./CustomScriptEdit.vue";
import WrenchOutlineIcon from "mdi-vue/WrenchOutline.vue";
import HelpIcon from "mdi-vue/Help.vue";

export default {
  components: {
    ActionBar,
    CustomScriptEdit,

    WrenchOutlineIcon,
    HelpIcon,
  },
  props: {
    customScripts: { type: Array, default: [] },
  },
  model: {
    prop: "customScripts",
  },
  methods: {
    addCustomScript() {
      if (this.customScripts.length > 0) {
        const last = this.customScripts[this.customScripts.length - 1];
        if (last.name === "" && last.script === "") return;
      }
      this.customScripts.push({
        name: "",
        script: "",
        type: "replace",
        __key: new Date().getTime().toString() + "-" + Math.random().toString(),
      });
    },
    removeCustomScript(i) {
      this.customScripts.splice(i, 1);
    },
    seeCustomScriptHelp() {
      window.open("/guide/#custom-scripts");
    },
  },
};
</script>

// website/src/components/CustomScripts.tsx
import ActionBar from "./ActionBar";
import CustomScriptEdit, { CustomScript } from "./CustomScriptEdit";
import WrenchOutlineIcon from "mdi-react/WrenchOutlineIcon";
import HelpIcon from "mdi-react/HelpIcon";

function seeCustomScriptHelp() {
  window.open("/about/guide/#custom-scripts");
}

export default function CustomScripts({
  customScripts,
  setCustomScripts,
}: {
  customScripts: CustomScript[];
  setCustomScripts: React.Dispatch<React.SetStateAction<CustomScript[]>>;
}) {
  const addCustomScript = () => {
    if (customScripts.length > 0) {
      const last = customScripts[customScripts.length - 1];
      if (last.name === "" && last.script === "") return;
    }

    setCustomScripts(old => [
      ...old,
      {
        name: "",
        script: "",
        type: "replace",
        __key: new Date().getTime().toString() + "-" + Math.random().toString(),
      },
    ]);
  };

  const removeCustomScript = (i: number) => {
    setCustomScripts(customScripts => {
      const newArr = [...customScripts];
      newArr.splice(i, 1);
      return newArr;
    });
  };

  return (
    <ActionBar
      Prepend={WrenchOutlineIcon}
      text={
        <>
          Custom Scripts
          <div style={{ marginBottom: "1.4em" }}>
            {customScripts.map((cs, i) => (
              <CustomScriptEdit
                key={cs.__key}
                value={customScripts[i]}
                onChange={newVal => {
                  const arr = [...customScripts];
                  arr[i] = newVal;
                  setCustomScripts(arr);
                }}
                onRemove={() => removeCustomScript(i)}
              />
            ))}
          </div>
        </>
      }
    >
      <button
        className="gitpkg-button"
        style={{ flex: "1 1 0" }}
        type="button"
        onClick={addCustomScript}
      >
        Add a custom script
      </button>
      <button
        className="gitpkg-button icon with-left"
        type="button"
        onClick={seeCustomScriptHelp}
      >
        <HelpIcon size={16} />
      </button>
    </ActionBar>
  );
}
