// docs/.vuepress/my-components/SelectDropdown.vue
<template>
  <v-select
    class="gitpkg-select"
    v-bind="$attrs"
    v-on="$listeners"
    :components="{ OpenIndicator }"
  />
</template>

<script>
import VSelect from "vue-select";
import ChevronDownIcon from "mdi-vue/ChevronDown.vue";
// import "vue-select/dist/vue-select.css";

export default {
  props: ["height"],
  components: {
    VSelect,
  },
  data() {
    return {
      OpenIndicator: {
        render: h =>
          h(ChevronDownIcon, { width: this.height, height: this.height }),
      },
    };
  },
};
</script>

// website/src/components/SelectDropdown.tsx
import Select from "react-select";
// import ChevronDownIcon from "mdi-react/ChevronDownIcon";
import cx from "../cx";

const SelectDropdown = ({
  className,
  // height,
  ...props
}: React.ComponentProps<typeof Select> & { height: unknown }) => {
  return (
    <Select
      {...props}
      className={cx`gitpkg-select ${className}`}
      // TODO:
      // components={{
      //   DropdownIndicator: p => <ChevronDownIcon {...p} size={height} />,
      // }}
    />
  );
};

export default SelectDropdown as typeof Select;
